server:
  port: 32001
spring:
  application:
    name: config-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8401/eureka/,http://peer2:8402/eureka/,http://peer3:8403/eureka/
  instance:
    instance-id: client1

from: sit